export { default as Home } from './Home'
export { default as Cart } from './Cart'
export { default as SingleItem } from './SingleItem'
export { default as Delivery } from './Delivery'
export { default as Options } from './Options'
